name: Visual
on: [push]
jobs:
  visual:
    name: Visaul TF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: rover
        uses: Official-James/rover-terraform-action@main
        
      - name: Upload rover Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: rover
          path: "./rover.zip"
  
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    needs: visual
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - run: ls -hal
